server:
  port: 8769

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Documents/code/web/sample-projects/strain-config
  application:
    name: config-service


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8770/eureka
  instance:
    preferIpAddress: true